language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=1bb0be69381c8b6e42d99e142e0fae39ab7a83309d50c94444e8333610c58f60
    - SECRET_HMAC_KEY=secret

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
